### ISSUE TITLE
Job configuration in YAML

### ISSUE THREAD

**Issue by rshk** [rshk/jobcontrol#14]
Support job configuration in YAML.
- user-friendly configuration format
- flexible, allows us to easily extend serializable objects

See also #9

Proposed configuration example:

``` yaml
module: package_name.module_name
function: function_name
args:
    - one
    - two
kwargs:
    three: 3
    four: !retval 3
dependencies: [3]
# ... support for custom extensions here ...
```

It would also be nice to have a "natural key" field, allowing to keep in sync with an external configuration file...
