### ISSUE TITLE
Add support for custom "return value formatters"

### ISSUE THREAD

**Issue by rshk** [rshk/jobcontrol#24]
We need this for things like creating links to storage explorer / displaying stuff / downloading return values / ...
## Use cases
- crawler jobs, containing connection to db:
  - "view" -> link to storage explorer app
  - "download" -> zip / tar archive containing the whole database contents
- "import preview" jobs: we need to precalculate changes that will be made -> store somewhere -> display them to the user in a nice interface.
## Configuration

Many functions can be "generic" and then accept some configuration; for example, the "link to storage" formatter requires the URL of the storage explorer application.

Configuration of formatters might look like:

``` yaml
retval_formatters:
  - cls: mypkg.mymodule:MyClass
    formatter: myotherpkg.myothermodule:my_formatter_function
  - cls: mypkg.mymodule:MyClass2
    formatter: myotherpkg.myothermodule:my_formatter_function2
```

Formatters can then be pre-processed with `functools.partial`:

``` yaml
retval_formatters:
  - cls: mypkg.mymodule:MyClass
    formatter: myotherpkg.myothermodule:my_formatter_function
    kwargs:
      base_url: "http://example.com/..."
```
